version: '3.8'

services:
  app:
    build: .  # Build from current directory
    container_name: app
    ports:
      - "5001:5000"  # Map port 5000 of the container to port 5000 on the host
    environment:
      MONGODB_URI: ${MONGODB_URI}  # MongoDB URI passed via environment variable
      JWT_SECRET: ${JWT_SECRET}    # JWT Secret key passed via environment variable
      PORT: 5000                   # Default port for the app
    env_file:
      - .env  # Load environment variables from a .env file
    depends_on:
      - mongo   # Ensure MongoDB is up before starting the app

  mongo:
    image: mongo:latest  # Use the official MongoDB image
    container_name: mongo-db
    ports:
      - "27017:27017"    # Expose MongoDB on port 27017
    volumes:
      - mongo-data:/data/db  # Persist data using a volume

# Volumes to persist MongoDB data across container restarts
volumes:
  mongo-data: